---
- name: configure backend server
  hosts: backend
  become: yes
  tasks:
    - name: disable nodejs
      ansible.builtin.command: dnf module disable nodejs -y

    - name: enable nodejs 20
      ansible.builtin.command: dnf module enable nodejs:20 -y

    - name: start nodejs  
      ansible.builtin.command: dnf install nodejs -y

    - name: create app user
      ansible.builtin.user: 
        name: expense
        state: present

    - name: create app dir
      ansible.builtin.file:
        path: /app
        state: directory
        mode: '0755'    