---
- name: Provision EC2 instance and update r53
  hosts: localhost
  connection: local
  gather_facts: no
  vars: 
    region: us-east-1
    image_id: ami-0220d79f3f480ecf5
    instance_type: t3.micro
    security_id: sg-0ff527a822e6f1e16
    record_name: "mysql"
    server_zone: dawgs.online
    region_id: us-east-1

  tasks:
    - name: Create EC2 instance
      amazon.aws.ec2_instance: 
        image_id: "{{ image_id }}"
        instance_type: "{{ instance_type }}"
        security_group: "{{ security_id }}"
        region: "{{ region_id }}"
        tags:
          Name: "{{ record_name }}"
        state: present
      register: ec2_output
      - debug:
        var: ec2_output


    - name: create r53 record
      amazon.aws.route53:
        state: present 
        zone: "{{ server_zone }}"
        record: "{{ record_name }}.{{ server_zone }}"
        type: A
        ttl: 1
        value: "{{ item.private_ip }}"
        overwrite: true
      with_items: "{{ ec2_output.instances }}"         