---
- name: Provision EC2 instance and update r53
  hosts: localhost
  connection: local
  gather_facts: no
  vars: 
    region: us-east-1
    image_id: ami-0220d79f3f480ecf5
    instance_type: t3.micro
    security_id: sg-0ff527a822e6f1e16
    public_record:
      - mysql
      - backend
    private_record:
      - frontend  
    server_zone: dawgs.online
    region_id: us-east-1

  tasks:
    - name: Create EC2 instance
      amazon.aws.ec2_instance: 
        image_id: "{{ image_id }}"
        instance_type: "{{ instance_type }}"
        security_group: "{{ security_id }}"
        region: "{{ region_id }}"
        tags:
          Name: "{{ item }}"
        state: present
      loop: "{{ record_name }}"  
      register: ec2_output

    # - name: print the output
    #   ansible.builtin.debug:
    #     var: ec2_output 

    - name: create r53 record
      amazon.aws.route53:
        state: present 
        zone: "{{ server_zone }}"
        record: "{{ item.item }}.{{ server_zone }}"
        type: A
        ttl: 1
        value: "{{ item.instances[0].private_ip_address }}"
        overwrite: true
      loop: "{{ ec2_output.results }}"         

    - name: create record for route53 #Punlic IP for frontend
      amazon.aws.route53:
        state: present
        zone: "{{ server_zone }}"
        record: "{{ item.item }}.{{ server_zone }}"
        type: A
        ttl: 1
        value: "{{ item.instance[0].public_ip_address }}"
        overwrite: true
      loop: "{{ ec2_output.results }}"  